displayName: rewritebody
type: middleware
import: github.com/traefik/plugin-rewritebody
summary: Rewrites the body of HTTP requests

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  lastModified: true
  rewrites:
    - regex: "foo"
      replacement: "bar"
    - regex: "</body>"
      replacement: "<span>injected</span> </body>"
